# Generated by Django 5.1 on 2024-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caritem',
            old_name='product',
            new_name='movie_name',
        ),
    ]
