# Generated by Django 5.1 on 2024-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_rename_product_caritem_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caritem',
            old_name='cart',
            new_name='cart_name',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
